<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RawMaterialSeeder extends Seeder
{
    public function run(): void
    {
        // Get category IDs
        $categories = DB::table('raw_material_categories')->pluck('category_id', 'category_name');
        // Get supplier IDs
        $suppliers = DB::table('suppliers')->pluck('supplier_id', 'company_name');

        $materials = [
            // Tissus
            [
                'material_code' => 'TIS-001',
                'material_name' => 'Tissu Jacquard Premium',
                'category_id' => $categories['Tissus'],
                'description' => 'Tissu Jacquard de haute qualité pour matelas',
                'unit_of_measure' => 'meter',
                'min_stock_level' => 500,
                'max_stock_level' => 2000,
                'current_stock' => 1200.50,
                'unit_cost' => 45.75,
                'supplier_id' => $suppliers['Textile Maroc SA'],
                'location_in_warehouse' => 'Aisle 1, Shelf B',
                'notes' => 'Couleur: Blanc',
                'is_active' => true,
            ],
            [
                'material_code' => 'TIS-002',
                'material_name' => 'Tissu Coton Respirant',
                'category_id' => $categories['Tissus'],
                'description' => 'Tissu 100% coton pour couverture matelas',
                'unit_of_measure' => 'meter',
                'min_stock_level' => 300,
                'max_stock_level' => 1500,
                'current_stock' => 800.25,
                'unit_cost' => 38.90,
                'supplier_id' => $suppliers['Textile Maroc SA'],
                'location_in_warehouse' => 'Aisle 1, Shelf C',
                'notes' => 'Anti-acarien',
                'is_active' => true,
            ],
            [
                'material_code' => 'TIS-003',
                'material_name' => 'Tissu Ticking',
                'category_id' => $categories['Tissus'],
                'description' => 'Tissu spécial pour housse matelas',
                'unit_of_measure' => 'meter',
                'min_stock_level' => 400,
                'max_stock_level' => 1800,
                'current_stock' => 950.75,
                'unit_cost' => 52.30,
                'supplier_id' => $suppliers['Textile Maroc SA'],
                'location_in_warehouse' => 'Aisle 1, Shelf A',
                'notes' => 'Imperméable',
                'is_active' => true,
            ],

            // Mousses
            [
                'material_code' => 'MOU-001',
                'material_name' => 'Mousse HR 40kg/m³',
                'category_id' => $categories['Mousses'],
                'description' => 'Mousse haute résilience densité 40kg/m³',
                'unit_of_measure' => 'kg',
                'min_stock_level' => 1000,
                'max_stock_level' => 5000,
                'current_stock' => 3200.00,
                'unit_cost' => 85.50,
                'supplier_id' => $suppliers['Mousse Pro'],
                'location_in_warehouse' => 'Aisle 3, Zone Mousse',
                'notes' => 'Pour noyau matelas',
                'is_active' => true,
            ],
            [
                'material_code' => 'MOU-002',
                'material_name' => 'Mousse Memory Foam',
                'category_id' => $categories['Mousses'],
                'description' => 'Mousse à mémoire de forme',
                'unit_of_measure' => 'kg',
                'min_stock_level' => 500,
                'max_stock_level' => 2500,
                'current_stock' => 1500.50,
                'unit_cost' => 120.75,
                'supplier_id' => $suppliers['Mousse Pro'],
                'location_in_warehouse' => 'Aisle 3, Zone Spéciale',
                'notes' => 'Température sensible',
                'is_active' => true,
            ],
            [
                'material_code' => 'MOU-003',
                'material_name' => 'Mousse Latex Naturel',
                'category_id' => $categories['Mousses'],
                'description' => 'Latex 100% naturel',
                'unit_of_measure' => 'kg',
                'min_stock_level' => 300,
                'max_stock_level' => 1500,
                'current_stock' => 850.25,
                'unit_cost' => 150.90,
                'supplier_id' => $suppliers['Mousse Pro'],
                'location_in_warehouse' => 'Aisle 3, Zone Latex',
                'notes' => 'Anti-allergique',
                'is_active' => true,
            ],

            // Ressorts
            [
                'material_code' => 'RES-001',
                'material_name' => 'Ressort Bonnell',
                'category_id' => $categories['Ressorts'],
                'description' => 'Ressort traditionnel Bonnell',
                'unit_of_measure' => 'piece',
                'min_stock_level' => 5000,
                'max_stock_level' => 25000,
                'current_stock' => 15000,
                'unit_cost' => 8.50,
                'supplier_id' => $suppliers['Springs International'],
                'location_in_warehouse' => 'Aisle 5, Pallet Zone',
                'notes' => 'Diamètre: 6cm',
                'is_active' => true,
            ],
            [
                'material_code' => 'RES-002',
                'material_name' => 'Ressort Pocket',
                'category_id' => $categories['Ressorts'],
                'description' => 'Ressort encapsulé individuel',
                'unit_of_measure' => 'piece',
                'min_stock_level' => 3000,
                'max_stock_level' => 15000,
                'current_stock' => 8500,
                'unit_cost' => 12.75,
                'supplier_id' => $suppliers['Springs International'],
                'location_in_warehouse' => 'Aisle 5, Zone Premium',
                'notes' => 'Haute qualité',
                'is_active' => true,
            ],

            // Bois
            [
                'material_code' => 'BOI-001',
                'material_name' => 'Planche Pin 2x4',
                'category_id' => $categories['Bois'],
                'description' => 'Planche de pin pour cadre matelas',
                'unit_of_measure' => 'meter',
                'min_stock_level' => 200,
                'max_stock_level' => 1000,
                'current_stock' => 600.00,
                'unit_cost' => 25.30,
                'supplier_id' => $suppliers['Bois du Maroc'],
                'location_in_warehouse' => 'Aisle 7, Zone Bois',
                'notes' => 'Longueur: 2m',
                'is_active' => true,
            ],
            [
                'material_code' => 'BOI-002',
                'material_name' => 'Contreplaqué 18mm',
                'category_id' => $categories['Bois'],
                'description' => 'Contreplaqué pour fond matelas',
                'unit_of_measure' => 'sheet',
                'min_stock_level' => 50,
                'max_stock_level' => 250,
                'current_stock' => 150,
                'unit_cost' => 185.00,
                'supplier_id' => $suppliers['Bois du Maroc'],
                'location_in_warehouse' => 'Aisle 7, Zone Panneaux',
                'notes' => 'Format: 122x244cm',
                'is_active' => true,
            ],

            // Rembourrage
            [
                'material_code' => 'REM-001',
                'material_name' => 'Fibre Polyester',
                'category_id' => $categories['Rembourrage'],
                'description' => 'Fibre synthétique pour rembourrage',
                'unit_of_measure' => 'kg',
                'min_stock_level' => 200,
                'max_stock_level' => 1000,
                'current_stock' => 650.75,
                'unit_cost' => 18.90,
                'supplier_id' => $suppliers['Textile Maroc SA'],
                'location_in_warehouse' => 'Aisle 9, Zone Fibre',
                'notes' => 'Non-allergique',
                'is_active' => true,
            ],
            [
                'material_code' => 'REM-002',
                'material_name' => 'Laine Mérinos',
                'category_id' => $categories['Rembourrage'],
                'description' => 'Laine naturelle pour matelas premium',
                'unit_of_measure' => 'kg',
                'min_stock_level' => 100,
                'max_stock_level' => 500,
                'current_stock' => 280.50,
                'unit_cost' => 95.50,
                'supplier_id' => $suppliers['Textile Maroc SA'],
                'location_in_warehouse' => 'Aisle 9, Zone Naturelle',
                'notes' => 'Premium qualité',
                'is_active' => true,
            ],

            // Accessoires
            [
                'material_code' => 'ACC-001',
                'material_name' => 'Fermeture Éclair N°5',
                'category_id' => $categories['Accessoires'],
                'description' => 'Fermeture éclair pour housse',
                'unit_of_measure' => 'meter',
                'min_stock_level' => 100,
                'max_stock_level' => 500,
                'current_stock' => 320.25,
                'unit_cost' => 4.75,
                'supplier_id' => $suppliers['Textile Maroc SA'],
                'location_in_warehouse' => 'Aisle 11, Petit Stock',
                'notes' => 'Couleur assortie',
                'is_active' => true,
            ],
            [
                'material_code' => 'ACC-002',
                'material_name' => 'Ruban Bordure',
                'category_id' => $categories['Accessoires'],
                'description' => 'Ruban pour finition bordure matelas',
                'unit_of_measure' => 'meter',
                'min_stock_level' => 200,
                'max_stock_level' => 1000,
                'current_stock' => 580.00,
                'unit_cost' => 2.30,
                'supplier_id' => $suppliers['Textile Maroc SA'],
                'location_in_warehouse' => 'Aisle 11, Zone Ruban',
                'notes' => 'Largeur: 5cm',
                'is_active' => true,
            ],

            // Chimiques
            [
                'material_code' => 'CHI-001',
                'material_name' => 'Colle Polyuréthane',
                'category_id' => $categories['Chimiques'],
                'description' => 'Colle pour assemblage mousse',
                'unit_of_measure' => 'liter',
                'min_stock_level' => 20,
                'max_stock_level' => 100,
                'current_stock' => 65.50,
                'unit_cost' => 45.80,
                'supplier_id' => $suppliers['Chemical Supplies'],
                'location_in_warehouse' => 'Aisle 13, Zone Chimique',
                'notes' => 'Sécurité: Gants requis',
                'is_active' => true,
            ],
            [
                'material_code' => 'CHI-002',
                'material_name' => 'Retardateur de Feu',
                'category_id' => $categories['Chimiques'],
                'description' => 'Traitement ignifuge',
                'unit_of_measure' => 'liter',
                'min_stock_level' => 15,
                'max_stock_level' => 80,
                'current_stock' => 42.75,
                'unit_cost' => 68.90,
                'supplier_id' => $suppliers['Chemical Supplies'],
                'location_in_warehouse' => 'Aisle 13, Zone Sécurité',
                'notes' => 'Certifié Norme FMVSS302',
                'is_active' => true,
            ],

            // Emballage
            [
                'material_code' => 'EMB-001',
                'material_name' => 'Film Plastique Étirable',
                'category_id' => $categories['Emballage'],
                'description' => 'Film pour emballage matelas',
                'unit_of_measure' => 'roll',
                'min_stock_level' => 50,
                'max_stock_level' => 250,
                'current_stock' => 145,
                'unit_cost' => 85.00,
                'supplier_id' => $suppliers['Chemical Supplies'],
                'location_in_warehouse' => 'Aisle 15, Zone Emballage',
                'notes' => 'Largeur: 2m',
                'is_active' => true,
            ],
            [
                'material_code' => 'EMB-002',
                'material_name' => 'Carton Ondulé',
                'category_id' => $categories['Emballage'],
                'description' => 'Carton pour emballage final',
                'unit_of_measure' => 'sheet',
                'min_stock_level' => 100,
                'max_stock_level' => 500,
                'current_stock' => 320,
                'unit_cost' => 12.50,
                'supplier_id' => $suppliers['Bois du Maroc'],
                'location_in_warehouse' => 'Aisle 15, Zone Carton',
                'notes' => 'Format: 200x140cm',
                'is_active' => true,
            ],
        ];

        foreach ($materials as $material) {
            DB::table('raw_materials')->insert([
                'material_code' => $material['material_code'],
                'material_name' => $material['material_name'],
                'category_id' => $material['category_id'],
                'description' => $material['description'] ?? null,
                'unit_of_measure' => $material['unit_of_measure'],
                'min_stock_level' => $material['min_stock_level'],
                'max_stock_level' => $material['max_stock_level'],
                'current_stock' => $material['current_stock'],
                'unit_cost' => $material['unit_cost'],
                'supplier_id' => $material['supplier_id'],
                'location_in_warehouse' => $material['location_in_warehouse'],
                'notes' => $material['notes'],
                'is_active' => $material['is_active'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    
        $this->command->info('✅ 20 matières premières créées.');
    }
}
